### ISSUE TITLE
Workshop paper on improvements & limitations to MADDNESS

### ISSUE THREAD

**Issue by calvinmccarter** [joennlae/halutmatmul#4]
You might be interested in this workshop paper I worked on, exploring improvements & limitations to MADDNESS: http://calvinmccarter.com/papers/snn2022-lookups.pdf . We'll be presenting it as a poster at the Sparsity in Neural Networks workshop this week: https://www.sparseneural.net/home .

**Comment by joennlae** [comment]
Hi @calvinmccarter 

Thank you for the suggestion. I read it and agree with your assessment, especially with: "_We suggest that future research focus on improving the MADDNESS hash function, which appears to be an accuracy bottleneck._". If you want to use more data to back up that statement, feel free to use my results in addition to yours.

I am thinking about the `LeViT` results:

Explanation of the table.
<img width="1273" alt="Screenshot 2022-07-12 at 10 20 44" src="https://user-images.githubusercontent.com/1493766/178444361-4832005d-9ab6-43bd-961b-5f1e3b2fbd71.png">

**MADDness**: Is the in the paper described encoding algorithm.
**DT**: Using the same hashed binary decision tree, the learning is top-down instead of bottom-up. First building the centroids and then mapping the hash function with a decision tree classifier. 
https://github.com/joennlae/halutmatmul/blob/d48ac5533d5e2d3d4c8d4e592cdd6eb3d749ccc3/src/python/halutmatmul/decision_tree_and_pq.py#L201-L207
**PQ**: Product quantization: mapping the input vector to the closest prototype. So it is essentially the perfect encoding function.

Knowing this we can say pretty exact how much we could gain with a better encoding function or in your words: how big the accuracy bottleneck is :-). 

<img width="1257" alt="Screenshot 2022-07-12 at 10 29 24" src="https://user-images.githubusercontent.com/1493766/178446183-fcdd567a-a68c-487a-bb30-891957ab5707.png">

ResNet-50 results show the accuracy bottleneck.

I wish you a good presentation :-)

**Comment by calvinmccarter** [comment]
@joennlae, thanks -- this analysis is so helpful!
